title: catgirl owo
description: a weeb theme for your jekyll site OwO

# build settings

theme: catgirl

plugins:
  - jekyll-feed
  - jekyll-archives

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  subpages:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
  - scope:
      path: ""
      type: subpages
    values:
      layout: default
      permalink: /:title
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      permalink: /projects/:title

compress_html:
  clippings: all
  comments: all
  endings: all
  profiles: false
  blanklines: false
  ignore:
    envs: [development]

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE.txt
